version: '3'

services:
  match_web:
    build: .
    command: python3 match_ms/manage.py runserver 0.0.0.0:7003
    volumes:
      - .:/code
    ports:
      - "7003:7003"

  team_web:
    build: .
    command: python3 team_ms/manage.py runserver 0.0.0.0:7001
    volumes:
      - .:/code
    ports:
      - "7001:7001"

  player_web:
    build: .
    command: python3 player_ms/manage.py runserver 0.0.0.0:7002
    volumes:
      - .:/code
    ports:
      - "7002:7002"
