version: '3'

services:
  db:
    image: postgres:alpine
  
  matchweb:
    image: arnoldnonstop/match_microservice
    command: bash -c "python3 manage.py makemigrations & python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:7003"
    # volumes:
    #   - .:/code
    ports:
      - "7003:7003"
    depends_on:
      - "db"

  teamweb:
    image: arnoldnonstop/team_microservice
    command: bash -c "python3 manage.py makemigrations & python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:7001"
    # volumes:
    #   - .:/code
    ports:
      - "7001:7001"
    depends_on:
      - "db"

  playerweb:
    image: arnoldnonstop/player_microservice
    command: bash -c "python3 manage.py makemigrations & python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:7002"
    # volumes:
    #   - .:/code
    ports:
      - "7002:7002"
    depends_on:
      - "db"
