version: '3'

services:
  db:
    image: postgres:alpine
  team_ms_web:
    build: .
    # image: arnoldnonstop/team_microservice:latest
    command: bash -c "python3 manage.py makemigrations & python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:7003"
    volumes:
      - .:/code
    ports:
      - "7003:7003"
    depends_on:
      - db
